### ISSUE TITLE
安装了CallKiller后，在Cydia安装或卸载别的插件时闪退

### ISSUE THREAD

**Issue by kuretru** [laoyur/CallKiller-iOS#1]
安装版本：1.1.1@BigBoss
安装了CallKiller后，在Cydia安装或卸载别的插件时会自动重启SpringBoard，这会使得部分插件安装后在Cydia提示"半安装问题"

**Comment by androidcn** [comment]
貌似解决了

**Comment by laoyur** [comment]
BigBoss周末更新慢得一腿，总算发布了。1.2.1已经修复半安装和卸载残留的问题，抱歉给大家带来了麻烦  :(
