### ISSUE TITLE
希望增加快速全选

### ISSUE THREAD

**Issue by androidcn** [laoyur/CallKiller-iOS#2]
希望增加快速全选和搜索功能，实在太多省市

**Comment by laoyur** [comment]
可以有

**Comment by laoyur** [comment]
将会很快在1.3.0得到支持

**Comment by androidcn** [comment]
11.3.1 总是不成功

**Comment by laoyur** [comment]
@androidcn ???

**Comment by androidcn** [comment]
拦截不成功

handoff 过来的来电

**Comment by laoyur** [comment]
什么意思，这个功能我没用过，能解释详细一点吗
来电号码什么特征

**Comment by laoyur** [comment]
说明handoff过来时，走的不是`SBTelephonyManager.callEventHandler`接口
然而我暂时没有精力去追踪这个问题，以后有空了再看看

**Comment by androidcn** [comment]
全选和反选出现bug
有时无法反选

全选后，再去搜索其它城市进行反选，出现问题

**Comment by laoyur** [comment]
我根本就没有做反选功能啊，只给全选，有过滤条件时全选按钮禁用
现在的设计中，挺难处理反选的，比较混乱

**Comment by laoyur** [comment]
[callkiller-1.3.1.deb.zip](https://github.com/laoyur/CallKiller-iOS/files/2237787/callkiller-1.3.1.deb.zip)
装了试下，先看旧的配置有没有自动被纠正，再试各种选择的情况

**Comment by laoyur** [comment]
晕，这deb什么鬼，postinst脚本我没作改动啊
还有更多出错信息吗，完全装不上去？

**Comment by androidcn** [comment]
我直接filza安装，出错，没其他了

**Comment by androidcn** [comment]
那是错误信息

其实程序安装成功

测试了一下

全选后，搜索 广东，反选

成功

全部反选 这个功能不行

**Comment by laoyur** [comment]
你的最后一句「全部反选」，期望中的操作是什么样的，是指之前全选了，再点「全选按钮」要变成「全部未选」的状态吗？

**Comment by androidcn** [comment]
对的，重置最初状态，就是全选按钮文字变成取消全选

**Comment by laoyur** [comment]
[callkiller-1.3.2.deb.zip](https://github.com/laoyur/CallKiller-iOS/files/2237929/callkiller-1.3.2.deb.zip)

have a try

**Comment by androidcn** [comment]
成功，可以发布了

**Comment by androidcn** [comment]
不行，固话可以保存选项
移动电话 选择后，再进去是没保存的

**Comment by laoyur** [comment]
详细测试步骤是啥，我没试出问题来

**Comment by androidcn** [comment]
https://youtu.be/2zanJu5sJho

Checkitout

**Comment by laoyur** [comment]
@androidcn 移步到另一个issue里讨论吧，上传了打log的包
