### ISSUE TITLE
ios 11.0.1 安装1.1.0之后 springboard无限重启

### ISSUE THREAD

**Issue by name327** [laoyur/CallKiller-iOS#3]
RT ， 使用dpkg -i 安装。 springboard无限重启之后，使用ssh 到手机然后， 执行 dpkg -r  删除后，springboard 不重启了。 但是桌面有空白图标 callkiller-gui。

**Comment by laoyur** [comment]
晚点我给个带log的版本你试试。
桌面空白图标是因为1.1.0版没有加卸载后清理的脚本。1.2.1处理了这个问题

手动清空图标，只需要ssh进去执行uicache即可

**Comment by laoyur** [comment]
[callkiller-1.2.3.deb.zip](https://github.com/laoyur/CallKiller-iOS/files/2222694/callkiller-1.2.3.deb.zip)
试下这个包，里面打了log
dpkg -i 安装，然后 killall SpringBoard
出现反复重启现象后，卸载掉，再把/var/mobile/callkiller.log文件发给我看下

**Comment by name327** [comment]
这么久才看到， 不好意思。 测试了， 可以了。

**Comment by laoyur** [comment]
😓，都没让我明白到底哪里出了问题
更新到1.3.5了，等大老板更新，我的测试源今天刚搭好没多久，服务器就挂了，真特么及时
