### ISSUE TITLE
[Request]拦截所有固话

### ISSUE THREAD

**Issue by androidcn** [laoyur/CallKiller-iOS#4]
[Request]拦截所有固话
但正常的10000 10086 不能拦截

**Comment by laoyur** [comment]
拦截所有固话，目前不是根据区号来的嘛，10086本身不带区号，自然不会被拦截
你想要的是带区号的10086不被拦截是吧？

每个人的需求不一样，你这个需求应该可以通过白名单功能解决。但暂时没有计划加这个，要做的话，也是优先级较低的。

**Comment by androidcn** [comment]
这个不是搞好了吗？可以close

**Comment by laoyur** [comment]
说实话你的原始request我并没有太看懂😝
