### ISSUE TITLE
1.3.2 启用后自动变成未启用？

### ISSUE THREAD

**Issue by bao3** [laoyur/CallKiller-iOS#6]
今天更新了发现，启用后无论何种操作，最终都会自动变成禁用状态，希望可以修复一下。系统为 11.3.1

**Comment by laoyur** [comment]
#2 
是跟这个issue情况一样吗？ui里修改后，当时一切正常，退出再进，就丢了？

麻烦帮忙验证下：
ui里修改后，退出，备份一下/var/mobile/callkiller/callkiller-pref.json这个文件，再打开ui，比对一下/var/mobile/callkiller/callkiller-pref.json和之前的备份，正常情况应该不会发生任何变化

**Comment by laoyur** [comment]
[callkiller-1.3.3.deb.zip](https://github.com/laoyur/CallKiller-iOS/files/2239490/callkiller-1.3.3.deb.zip)
filza装一下这个版本，记得装完后手动respring
再运行一下gui，修改下配置，退出，再打开
之后把/var/mobile/callkiller/callkiller.log发上来我看下

**Comment by laoyur** [comment]
[callkiller-1.3.4.deb.zip](https://github.com/laoyur/CallKiller-iOS/files/2239842/callkiller-1.3.4.deb.zip)
6、7个人给我反馈了问题，但还木有任何人给log我…… ┓( ´∀` )┏  
有缘人试一下1.3.4吧，我显式修改了文件权限，虽然我并不确定是不是这方面的问题
记得装完后手动respring

**Comment by Daemon008** [comment]
上午不曾有空，中午试了一下1.3.4，可以正常启用了。之前的黑名单设置也回来了。

**Comment by laoyur** [comment]
@Daemon008 很好，看来是权限问题，deb安装时创建了/var/mobile/callkiller目录，然而可能它是root权限，奇怪的是我这里测试并不是root权限。总之看上去是修好了，准备提交大老板

**Comment by bao3** [comment]
补充一下，最好在 documents 下建立文件夹，

发自我的 iPhone

**Comment by laoyur** [comment]
从测试源安装试试：
laoyur.com/cydia

**Comment by Riol1** [comment]
安装了 测试安装源里面的1.3.5版本终于正常了

laoyur <notifications@github.com> 于2018年7月31日周二 上午9:43写道：

**Comment by Riol1** [comment]
安装了测试安装源里面的版本一切正常使用了
