### ISSUE TITLE
拦截根本不起作用

### ISSUE THREAD

**Issue by androidcn** [laoyur/CallKiller-iOS#7]
不起作用
防骚扰大师 都安装的

**Comment by laoyur** [comment]
起没起作用，自己加一个号码做黑名单，打一下一试便知
如果不起作用，可能：
1. tweak根本没加载 -- 尝试respring
2. 配置文件没写成功 -- 尝试从大老板重装 1.3.5

如果起作用，但关键词拦截不起作用，自行确认 `/var/mobile/Library/CallDirectory/CallDirectory.db`数据库是否正常。正常情况下这个db应该很大，接近百兆，里面是助手类软件写入的各号码的label对应关系，可以用filza的sqlite浏览器打开

**Comment by androidcn** [comment]
测试了黑名单，不行，我是英文界面

**Comment by laoyur** [comment]
bigboss装1.4.1，这个版本我忘记关log了，所以正好可以用来给你测试
查看 /var/mobile/callkiller.log 这个文件有没有生成
打个电话，再看里面有没有日志生成
1. 如果没创建这个文件 -- 说明tweak没加载
2. 如果有这个文件，但没有内容

case 1：不是我的问题，其他人都能正常加载tweak的
case 2：ui里面修改一下[启用]这个开关，然后观察 /var/mobile/callkiller/callkiller-pref.json里面的enabled字段有没有变化。如果没变，说明写入配置失败，检查一下/var/mobile/callkiller文件夹owner是否是mobile

**Comment by androidcn** [comment]
成功了，问题出在，enable

**Comment by laoyur** [comment]
@androidcn 😓
